---
title: "PA1_template.Rmd"
author: "Vipul Thapa"
date: "July 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

getwd()
setwd("F:/R Programming Certification/Course 5/repdata%2Fdata%2Factivity")
getwd()
data <- read.csv("activity.csv",header = TRUE, sep = ",", na.strings = "NA")
head(data)
summary(data)
str(data)
str(data)
mean(data$steps,na.rm = TRUE)

NA_Index <- is.na(as.character(data$steps))
data_no_NA <- data[!NA_Index,]
data_no_NA
steps_each_day <- aggregate(steps ~ date, data = data_no_NA, sum)
steps_each_day
colnames(steps_each_day) <- c("date","steps")
hist(as.numeric(steps_each_day$steps),breaks = 20,col="red",xlab="Number of Steps",main="Histogram of the total number of steps taken each day")
mean(steps_each_day$steps)
median(steps_each_day$steps)


steps_by_interval <- aggregate(steps ~ interval, data, mean)
plot(steps_by_interval$interval,steps_by_interval$steps, type="l", xlab="Interval", ylab="Number of Steps",main="Average Number of Steps per Day by Interval")


max_interval <- steps_by_interval[which.max(steps_by_interval$steps),1]
max_interval

NATotal <- sum(!complete.cases(data))
NATotal

StepsAverage <- aggregate(steps ~ interval, data = data, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(data)) {
  obs <- data[i, ]
  if (is.na(obs$steps)) {
    steps <- subset(StepsAverage, interval == obs$interval)$steps
  } else {
    steps <- obs$steps
  }
  fillNA <- c(fillNA, steps)
}
new_activity <- data
new_activity$steps <- fillNA

StepsTotalUnion <- aggregate(steps ~ date, data = new_activity, sum, na.rm = TRUE)
hist(StepsTotalUnion$steps, main = paste("Total Steps Each Day"), col="blue", xlab="Number of Steps")
#Create Histogram to show difference. 
hist(steps_by_day$steps, main = paste("Total Steps Each Day"), col="green", xlab="Number of Steps", add=T)
legend("topright", c("Imputed", "Non-imputed"), col=c("blue", "green"), lwd=10)

steps_by_day <- aggregate(steps ~ date, data, sum)

rmean <- mean(steps_by_day$steps)
rmean
rmedian <- median(steps_by_day$steps)
rmedian
rmeantotal <- mean(StepsTotalUnion$steps)
rmeantotal

rmediantotal <- median(StepsTotalUnion$steps)
rmediantotal
rmediandiff <- rmediantotal - rmedian
rmediandiff

rmediandiff <- rmediantotal - rmedian

rmeandiff <- rmeantotal - rmean
rmeandiff


weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
new_activity$dow = as.factor(ifelse(is.element(weekdays(as.Date(new_activity$date)),weekdays), "Weekday", "Weekend"))
StepsTotalUnion <- aggregate(steps ~ interval + dow, new_activity, mean)
library(lattice)
xyplot(StepsTotalUnion$steps ~ StepsTotalUnion$interval|StepsTotalUnion$dow, main="Average Steps per Day by Interval",xlab="Interval", ylab="Steps",layout=c(1,2), type="l")

